Update repo-dispatcher.yml

diff --git a/.github/workflows/repo-dispatcher.yml b/.github/workflows/repo-dispatcher.yml
--- a/.github/workflows/repo-dispatcher.yml
+++ b/.github/workflows/repo-dispatcher.yml
@@ -51,13 +51,27 @@ jobs:
     - name: Trigger Packages Update
       run: |
         gitdate=$(curl -H "Authorization: token ${{ secrets.TOKEN_KIDDIN9 }}" -s "https://api.github.com/repos/kiddin9/openwrt-packages/actions/runs" | jq -r '.workflow_runs[0].created_at')
+        if [[ -z "$gitdate" ]]; then  
+        echo "Failed to get gitdate"  
+        exit 1  
+        fi  
         gitdate=$(date -d "$gitdate" +%s)
+        if [[ -z "$gitdate" ]]; then  
+        echo "Failed to convert gitdate"  
+        exit 1  
+        fi 
         now=$(date -d "$(date)" +%s)
+         if [[ -z "$now" ]]; then  
+         echo "Failed to get current timestamp"  
+         exit 1  
+         fi  
         if [[ $(expr $gitdate + 120) < $now ]]; then
         curl -X POST https://api.github.com/repos/kiddin9/openwrt-packages/dispatches \
         -H "Accept: application/vnd.github.everest-preview+json" \
         -H "Authorization: token ${{ secrets.TOKEN_KIDDIN9 }}" \
         --data '{"event_type": "update"}'
+        else  
+        echo "No update needed" 
         fi
 
     - name: Trigger Compile
